/*
The following is the structure of the .env file

MYSQL_HOST = 
MYSQL_USER = 
MYSQL_PASSWORD = 
MYSQL_DATABASE = 
JWT_SECRET = 
CLOUDWATCH_GROUP_NAME = 
CLOUDWATCH_ACCESS_KEY = 
CLOUDWATCH_SECRET_ACCESS_KEY = 
CLOUDWATCH_REGION = 
*/
