/*
The following is the structure of the .env file

MYSQL_HOST = 
MYSQL_USER = 
MYSQL_PASSWORD = 
MYSQL_DATABASE = 
JWT_SECRET = 
CLOUDWATCH_GROUP_NAME = my-word-space-node-express-app
CLOUDWATCH_ACCESS_KEY = AKIARHW6TFCGYLEYEIGV
CLOUDWATCH_SECRET_ACCESS_KEY = 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
CLOUDWATCH_REGION = eu-central-1
*/
